name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  UTs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: UTs
      run: cd Test && make run
